# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changehistory',
            name='error',
        ),
        migrations.RemoveField(
            model_name='changehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='error',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='error',
            name='change_description',
        ),
        migrations.RemoveField(
            model_name='error',
            name='config_id',
        ),
        migrations.RemoveField(
            model_name='error',
            name='env_version',
        ),
        migrations.RemoveField(
            model_name='error',
            name='fault_area',
        ),
        migrations.RemoveField(
            model_name='error',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='error',
            name='jenkins_path',
        ),
        migrations.RemoveField(
            model_name='error',
            name='script_label',
        ),
        migrations.RemoveField(
            model_name='error',
            name='software_label',
        ),
        migrations.RemoveField(
            model_name='error',
            name='state',
        ),
        migrations.RemoveField(
            model_name='error',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='error',
            name='tc_number',
        ),
        migrations.RemoveField(
            model_name='error',
            name='test_environment',
        ),
        migrations.AlterField(
            model_name='error',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
